### ISSUE TITLE
add project:<...> tag to Flickr collections

### ISSUE THREAD

**Issue by rvosa** [naturalis/nbclassify#14]
Butterflies and orchids are now distinguished from one another by, respectively, using the `id_date` tag to harvest butterflies, or the `section` tag to harvest orchids. This is an ugly hack that will fail once more projects are added (e.g. mosquitoes). Better would be to have a `project:orchids` or `project:butterflies` tag.

**Comment by Saskiadv** [comment]
All pictures that are currently on Flickr are tagged with a project:<...> tag, according to the dataset they belong to (orchids/butterflies/mosquitoes).
