### ISSUE TITLE
segment butterfly images

### ISSUE THREAD

**Issue by rvosa** [naturalis/nbclassify#7]
As of commit https://github.com/naturalis/imgpheno/commit/d9935f00375095729cd8de703f749f1180a92535 there is now a prototype implementation of 'simple' segmentation based only on a region of interest: everything within the ROI is retained, everything outside is masked. 

We have concluded that this is probably good enough for segmenting the butterfly image because their background is static. (Also, it would be harder to apply GrabCut on the butterfly images because they have no depth of focus, and that is what GrabCut is partially based on).

Now that the butterfly images have been annotated on Flickr, the next step should be to do a test run of the simple segmentation to see if we can trim all the images to the same ROI box.

**Comment by Saskiadv** [comment]
The images with the largest butterflies or with the butterflies that are most out of centre from the bottom left quadrant are used to determine the ROI for simple segmentation.

When the images are not scaled (so --max-size is not set), the ROI can be "0, 900, 2350, 2500".
When --max-size is set to 1800 (so the whole image is visible on a screen), the ROI can be "0, 150, 420, 465".

The used images come from the 382 butterfly pictures on the Flickr account. If there are larger butterflies or butterflies more out of centre from the bottom left quadrant in future images, a new ROI might have to be determined.
