### ISSUE TITLE
extract features from butterfly images

### ISSUE THREAD

**Issue by rvosa** [naturalis/nbclassify#8]
As a first step we should at least extract the following features from the butterfly images (after #7 is completed):
1. the histogram function that we used for the orchids.
2. the [SURF](https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_feature2d/py_surf_intro/py_surf_intro.html#surf) algorithm

Once we have these features extracted they need to be analyzed by @WvTongeren and Mengke.

**Comment by Saskiadv** [comment]
The nbc-harvest-images script is updated so it works for the butterflies as well. A database of the butterfly information is made and now stored in the archive-butterfly folder in the nbclassify-data repository.

"nbc_create_mean_bgr_file.py" is added to the scripts to use the histogram function and make a datafile of it. 
The datafile that came out is also stored in the the archive-butterflies folder of the nbclassify-data repository.
